routes/web.php
    // Route::get('musisi-platform/syncTrack', 'Admin\MusisiPlatformController@syncTrack')->name('musisi-platform.syncTrack');
    // Route::get('musisi-platform/syncTrackMusician', 'Admin\MusisiPlatformController@syncTrackMusician')->name('musisi-platform.syncTrackMusician');
    // Route::get('musisi-platform/syncBand', 'Admin\MusisiPlatformController@syncBand')->name('musisi-platform.syncBand');
});

Route::prefix('musisi-platform')->group(static function () {
    Route::get('/', 'Admin\MusisiPlatformController@index')->name('musisi-platform');
    Route::get('/track', 'Admin\MusisiPlatformController@track')->name('musisi-platform.track');
    Route::get('/trackMusician', 'Admin\MusisiPlatformController@trackMusician')->name('musisi-platform.trackMusician');
    Route::get('/band', 'Admin\MusisiPlatformController@band')->name('musisi-platform.band');
    Route::get('/data', 'Admin\MusisiPlatformController@data')->name('musisi-platform.data');
    Route::get('/dataBand', 'Admin\MusisiPlatformController@dataBand')->name('musisi-platform.dataBand');
    Route::get('/dataTrack', 'Admin\MusisiPlatformController@dataTrack')->name('musisi-platform.dataTrack');
    Route::get('/dataTrackMusician', 'Admin\MusisiPlatformController@dataTrackMusician')->name('musisi-platform.dataTrackMusician');
    Route::get('musisi-platform/sync', 'Admin\MusisiPlatformController@sync')->name('musisi-platform.sync');
    Route::get('musisi-platform/syncTrack', 'Admin\MusisiPlatformController@syncTrack')->name('musisi-platform.syncTrack');
    Route::get('musisi-platform/syncTrackMusician', 'Admin\MusisiPlatformController@syncTrackMusician')->name('musisi-platform.syncTrackMusician');
    Route::get('musisi-platform/syncBand', 'Admin\MusisiPlatformController@syncBand')->name('musisi-platform.syncBand');

    // Route::get('/data', 'Admin\BannerController@data')->name('banner.data');
    // Route::get('/create', 'Admin\BannerController@create')->name('banner.create');
    // Route::post('/store', 'Admin\BannerController@store')->name('banner.store');
    // Route::get('/edit', 'Admin\BannerController@edit')->name('banner.edit');
    // Route::post('/update', 'Admin\BannerController@update')->name('banner.update');
    // Route::get('/delete', 'Admin\BannerController@delete')->name('banner.delete');
    // Route::post('/destroy', 'Admin\BannerController@destroy')->name('banner.destroy');
    // Route::get('/show', 'Admin\BannerController@show')->name('banner.show');
});

Route::get('/home', 'HomeController@index')->name('home');

//Banner
Route::prefix('banner')->group(static function () {
    Route::get('/', 'Admin\BannerController@index')->name('banner');
    Route::get('/data', 'Admin\BannerController@data')->name('banner.data');
    Route::get('/create', 'Admin\BannerController@create')->name('banner.create');
    Route::post('/store', 'Admin\BannerController@store')->name('banner.store');
    Route::get('/edit', 'Admin\BannerController@edit')->name('banner.edit');
    Route::post('/update', 'Admin\BannerController@update')->name('banner.update');
    Route::get('/delete', 'Admin\BannerController@delete')->name('banner.delete');
    Route::post('/destroy', 'Admin\BannerController@destroy')->name('banner.destroy');
    Route::get('/show', 'Admin\BannerController@show')->name('banner.show');
});

//genre
Route::prefix('genre')->group(static function () {
    Route::get('/', 'Admin\GenreController@index')->name('genre');
    Route::get('/data', 'Admin\GenreController@data')->name('genre.data');
    Route::get('/create', 'Admin\GenreController@create')->name('genre.create');
    Route::post('/store', 'Admin\GenreController@store')->name('genre.store');
    Route::get('/edit', 'Admin\GenreController@edit')->name('genre.edit');
    Route::post('/update', 'Admin\GenreController@update')->name('genre.update');
    Route::get('/delete', 'Admin\GenreController@delete')->name('genre.delete');
    Route::post('/destroy', 'Admin\GenreController@destroy')->name('genre.destroy');
    Route::get('/show', 'Admin\GenreController@show')->name('genre.show');
});

//event
Route::prefix('event')->group(static function () {
    Route::get('/', 'Admin\EventController@index')->name('event');
    Route::get('/data', 'Admin\EventController@data')->name('event.data');
    Route::get('/create', 'Admin\EventController@create')->name('event.create');
    Route::post('/store', 'Admin\EventController@store')->name('event.store');
    Route::get('/edit', 'Admin\EventController@edit')->name('event.edit');
    Route::post('/update', 'Admin\EventController@update')->name('event.update');
    Route::get('/delete', 'Admin\EventController@delete')->name('event.delete');
    Route::post('/destroy', 'Admin\EventController@destroy')->name('event.destroy');
    Route::get('/show', 'Admin\EventController@show')->name('event.show');
});

//compilation
Route::prefix('compilation')->group(static function () {
    Route::get('/', 'Admin\CompilationController@index')->name('compilation');
    Route::get('/data', 'Admin\CompilationController@data')->name('compilation.data');
    Route::get('/create', 'Admin\CompilationController@create')->name('compilation.create');
    Route::post('/store', 'Admin\CompilationController@store')->name('compilation.store');
    Route::get('/edit', 'Admin\CompilationController@edit')->name('compilation.edit');
    Route::post('/update', 'Admin\CompilationController@update')->name('compilation.update');
    Route::get('/delete', 'Admin\CompilationController@delete')->name('compilation.delete');
    Route::post('/destroy', 'Admin\CompilationController@destroy')->name('compilation.destroy');
    Route::get('/show', 'Admin\CompilationController@show')->name('compilation.show');
});

//podcast

//podcast

Route::prefix('podcast')->group(static function () {
    Route::get('/', 'Admin\PodcastController@index')->name('podcast');
    Route::get('/data', 'Admin\PodcastController@data')->name('podcast.data');
    Route::get('/create', 'Admin\PodcastController@create')->name('podcast.create');
    Route::post('/store', 'Admin\PodcastController@store')->name('podcast.store');
    Route::get('/edit', 'Admin\PodcastController@edit')->name('podcast.edit');
    Route::post('/update', 'Admin\PodcastController@update')->name('podcast.update');
    Route::get('/delete', 'Admin\PodcastController@delete')->name('podcast.delete');
    Route::post('/destroy', 'Admin\PodcastController@destroy')->name('podcast.destroy');
    Route::get('/show', 'Admin\PodcastController@show')->name('podcast.show');
});

Route::resource('podcast-categories','Admin\PodcastCategoryController');
// Route::resource('banner','Admin\BannerController');

//Caffe
Route::prefix('cafe')->group(static function () {
    Route::get('/', 'Admin\CafeController@index')->name('cafe');
    Route::get('/data', 'Admin\CafeController@data')->name('cafe.data');
    Route::get('/create', 'Admin\CafeController@create')->name('cafe.create');
    Route::post('/store', 'Admin\CafeController@store')->name('cafe.store');
    Route::get('/edit', 'Admin\CafeController@edit')->name('cafe.edit');
    Route::post('/update', 'Admin\CafeController@update')->name('cafe.update');
    Route::get('/delete', 'Admin\CafeController@delete')->name('cafe.delete');
    Route::post('/destroy', 'Admin\CafeController@destroy')->name('cafe.destroy');
    Route::get('/show', 'Admin\CafeController@show')->name('cafe.show');
    Route::get('/search-user', 'Admin\CafeController@search_user')->name('cafe.search.user');
    Route::get('/map', 'Admin\CafeController@map')->name('cafe.map');
});

//Caffe Menu
Route::prefix('cafe-menu')->group(static function () {
    Route::get('/', 'Admin\CafeMenuController@index')->name('cafe.menu');
    Route::get('/data', 'Admin\CafeMenuController@data')->name('cafe.menu.data');
    Route::get('/create', 'Admin\CafeMenuController@create')->name('cafe.menu.create');
    Route::post('/store', 'Admin\CafeMenuController@store')->name('cafe.menu.store');
    Route::get('/edit', 'Admin\CafeMenuController@edit')->name('cafe.menu.edit');
    Route::post('/update', 'Admin\CafeMenuController@update')->name('cafe.menu.update');
    Route::get('/delete', 'Admin\CafeMenuController@delete')->name('cafe.menu.delete');
    Route::post('/destroy', 'Admin\CafeMenuController@destroy')->name('cafe.menu.destroy');
    Route::get('/show', 'Admin\CafeMenuController@show')->name('cafe.menu.show');
});

//Caffe Image
Route::prefix('cafe-image-data')->group(static function () {
    Route::get('', 'Admin\CafeImageController@index')->name('cafe.image');
    Route::get('/data', 'Admin\CafeImageController@data')->name('cafe.image.data');
    Route::get('/create', 'Admin\CafeImageController@create')->name('cafe.image.create');
    Route::post('/store', 'Admin\CafeImageController@store')->name('cafe.image.store');
    Route::get('/edit', 'Admin\CafeImageController@edit')->name('cafe.image.edit');
    Route::post('/update', 'Admin\CafeImageController@update')->name('cafe.image.update');
    Route::get('/delete', 'Admin\CafeImageController@delete')->name('cafe.image.delete');
    Route::post('/destroy', 'Admin\CafeImageController@destroy')->name('cafe.image.destroy');
});

//Caffe Schedule
Route::prefix('cafe-schedule')->group(static function () {
    Route::get('', 'Admin\CafeScheduleController@index')->name('cafe.schedule');
    Route::get('/data', 'Admin\CafeScheduleController@data')->name('cafe.schedule.data');
    Route::get('/create', 'Admin\CafeScheduleController@create')->name('cafe.schedule.create');
    Route::post('/store', 'Admin\CafeScheduleController@store')->name('cafe.schedule.store');
    Route::get('/edit', 'Admin\CafeScheduleController@edit')->name('cafe.schedule.edit');
    Route::post('/update', 'Admin\CafeScheduleController@update')->name('cafe.schedule.update');
    Route::get('/delete', 'Admin\CafeScheduleController@delete')->name('cafe.schedule.delete');

app/Models/PodcastCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PodcastCategory extends Model
{
    //
    protected $table = 'podcast_category';
    protected $fillable = ['name','slug','enabled'];
}

app/Http/Controllers/Admin/PodcastCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\PodcastCategory;
use App\Services\Slug;
class PodcastCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $NewsCategories = PodcastCategory::orderBy('id','asc')->paginate(5);
  
        return view('admin.podcast-categories.index',compact('NewsCategories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.podcast-categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //        
        $data = $request->all();
        $request->validate([
            'name' => 'required',          
        ]);
        $slug = new Slug();
        $data['slug'] = $slug->createSlug($request->name);
        $data['enabled'] = true;
        

        PodcastCategory::create($data);
   
        return redirect()->route('podcast-categories.index')
                        ->with('success','category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(PodcastCategory $podcastCategory)
    {
        //
        
        return view('admin.podcast-categories.show',compact('podcastCategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(PodcastCategory $podcastCategory)
    {
       
        //
        return view('admin.podcast-categories.edit',compact('podcastCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PodcastCategory $podcastCategory)
    {
        //
         //
         $data = $request->all();
         $request->validate([
            'name' => 'required',           
        ]);
        $slug = new Slug();
        $data['slug'] = $slug->createSlug($request->name);
        $data['enabled'] = true;
        

        $podcastCategory->update($data);
   
  
        return redirect()->route('podcast-categories.index')
                        ->with('success','category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(PodcastCategory $podcastCategory)
    {
        //
        $podcastCategory->delete();
  
        return redirect()->route('podcast-categories.index')
                        ->with('success','category deleted successfully');
    }
}

resources/views/admin/podcast-categories/create.blade.php
@extends('layouts.admin')
  
@section('content')

<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-8  offset-md-2">
                <div class="card no-b  no-r">

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('podcast-categories.store') }}" method="POST">
    @csrf
    <div class="card no-b  no-r">
    <div class="card-body">
        <h5 class="card-title">Create Category</h5>
        <hr>
        <div class="form-row">
            <div class="col-md-8">
                <div class="form-group m-0">
                    <label for="name" class="col-form-label s-12">CATEGORY NAME</label>
                    <input name="name" id="name" placeholder="Enter Category Name" class="form-control r-0 light s-12 " type="text">
                </div>
            </div>
        </div>
    </div>
    
    <hr>
    <div class="card-body">
        <button type="submit" class="btn btn-primary btn-sm"><i class="icon-save mr-2"></i>Save Data</button>
    </div>
</div>
</form>      
</div>
</div>
</div>
</div>
@endsection

resources/views/admin/podcast-categories/edit.blade.php
@extends('layouts.admin')
  
@section('content')

<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-7  offset-md-2">
                <div class="card no-b  no-r">

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('podcast-categories.update',$podcastCategory->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="card no-b  no-r">
    <div class="card-body">
        <h5 class="card-title">Edit Category</h5>
        <hr>
        <div class="form-row">
            <div class="col-md-8">
                <div class="form-group m-0">
                    <label for="name" class="col-form-label s-12">CATEGORY NAME</label>
                    <input name="name" id="name" value="{{ $podcastCategory->name }}" placeholder="Enter Category Name" class="form-control r-0 light s-12 " type="text">
                </div>
            </div>
        </div>
    </div>
    
    <hr>
    <div class="card-body">
        <button type="submit" class="btn btn-primary btn-sm"><i class="icon-save mr-2"></i>Save Data</button>
    </div>
</div>
</form>      
</div>
</div>
</div>
</div>
@endsection

resources/views/admin/podcast-categories/index.blade.php
@extends('layouts/admin')

@section('content')

<div class="container-fluid my-2">
<div class="row">
            <div class="col-md-12">
          

                            @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
                 
                            <table class="table table-bordered" style="background:white;">
                                <tr>
                                    <td colspan="3">
                                       <h4> Podcasts Category </h4>
                                    </td>
                                    <td>
                                    <a class="btn btn-success pull-right" href="{{ route('podcast-categories.create') }}"> Create  Category</a>
                                    </td>
                                </tr>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th width="280px">Action</th>
                                </tr>
                                @foreach ($NewsCategories as $type)
                                <tr>
                                    <td>{{ $type->id }}</td>
                                    <td>{{ $type->name }}</td>
                                    <td>{{ $type->slug }}</td>
                                    <td>
                                        <form action="{{ route('podcast-categories.destroy',$type->id) }}" method="POST">

                                            <a class="btn btn-info" href="{{ route('podcast-categories.show',$type->id) }}">Show</a>

                                            <a class="btn btn-primary" href="{{ route('podcast-categories.edit',$type->id) }}">Edit</a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                                <tr>
                                     <td colspan="4" align="center">
                                    {!! $NewsCategories->links() !!}
                                    </td>
                                </tr>
                            </table>
             
        </div>
    </div>

</div>


@endsection

resources/views/admin/podcast-categories/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-7  offset-md-2">
                <div class="card no-b  no-r">

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h5> View detail</h5>
            </div>
            <hr>
            
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $podcastCategory->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Slug:</strong>
                {{ $podcastCategory->slug }}
            </div>
        </div>
    </div>
    </div>
    <hr>
    <div class="pull-right">
                <a class="btn btn-primary btn-sm" href="{{ route('podcast-categories.index') }}"> Back</a>
            </div>
</div>
</div>
</div>    
</div>    
@endsection