routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset_password/{token}', ['as' => 'password.reset', function($token)
{
    // implement your reset password route here!
}]);

Route::get('/','FrontendController@index')->name('homepage');
Route::get('/trackapps','FrontendController@track')->name('track');
Route::get('/artistapps','FrontendController@artist')->name('artist');
Route::get('/eventapps','FrontendController@event')->name('event');
Route::get('/cafeapps','FrontendController@cafe')->name('cafe');


Route::get('/berita', 'FrontendController@list');
Route::get('/berita/tag/{tag}', 'FrontendController@NewsByTag');
Route::get('/berita/cat/{cat}', 'FrontendController@NewsByCategory');
Route::get('/berita/view/{slug}', 'FrontendController@view');
Route::get('/podcasts1', 'FrontendController@listpodcast');
Route::get('/podcasts1/view/{slug}', 'FrontendController@viewpodcast');
Route::get('/contest', 'FrontendController@listcontest');

Route::get('/partnership', 'FrontendController@register');
Route::post('/store-register', 'FrontendController@storeRegister')->name('store-register');
Route::get('/success-register/{id}', 'FrontendController@viewSuccess')->name('succes-register');
Route::get('/verification-user/{id}', 'FrontendController@verifiedUser');

//Route::get('/constest/view/{slug}', 'FrontendController@viewpodcast');
Route::get('/about', 'FrontendController@about');
Route::get('/contact', 'FrontendController@contact');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
// $this->post('logout', 'Auth\LoginController@logout')->name('logout');


//user
Route::resource('user','Admin\UserController');

//business
// Route::get('//dashboard', 'DashboardController@index');

//admin
// Route::resource('business','Admin\BusinessController');
Route::resource('business-categories','Admin\BusinessCategoriesController');
Route::resource('partner','Admin\PartnerController');
Route::resource('list-business','Admin\ListBusinessController');


//news
Route::resource('news','Admin\NewsController');
Route::resource('news-categories','Admin\NewsCategoryController');


//musisi
// Route::get('musisi-platform/sync', 'Admin\MusisiPlatformController@sync')->name('musisi-platform.sync');
// Route::get('musisi-platform/syncTrack', 'Admin\MusisiPlatformController@syncTrack')->name('musisi-platform.syncTrack');
// Route::get('musisi-platform/syncBand', 'Admin\MusisiPlatformController@syncBand')->name('musisi-platform.syncBand');
// Route::resource('musisi-platform','Admin\MusisiPlatformController');

Route::prefix('business')->group(static function () {
    Route::get('/', 'Business\DashboardController@index')->name('business');

    Route::get('/employee', 'Business\EmployeeController@index')->name('business.employee');
    Route::get('/setting', 'Business\SettingController@index')->name('business.setting');

    // BusinessController
    Route::get('/list', 'Business\BusinessController@index')->name('business.list');
    Route::get('/create', 'Business\BusinessController@create')->name('business.create');
    Route::post('/store', 'Business\BusinessController@store')->name('business.store');
    Route::post('/edit', 'Business\BusinessController@update')->name('business.update');
    Route::post('/status', 'Business\BusinessController@updateStatus')->name('business.updateStatus');
    Route::get('/dashboard-business/{id}', 'Business\BusinessController@dashboardBusiness')->name('business.dashboard');
    Route::get('/detail/{id}', 'Business\BusinessController@detail')->name('business.detail');
    Route::get('/configuration/{id}', 'Business\BusinessController@configuration')->name('business.configuration');
    Route::get('/detail-order/{id}/{bId}', 'Business\BusinessController@detailOrder')->name('business.detailOrder');
    Route::get('/detail-track/{id}/{bId}', 'Business\BusinessController@detailMusic')->name('business.detailMusic');
    Route::get('/status/{id}/{bId}', 'Business\BusinessController@status')->name('business.status');
    Route::get('/edit/{id}', 'Business\BusinessController@edit')->name('business.edit');
    Route::get('/delete/{id}', 'Business\BusinessController@delete')->name('business.detele');
    Route::get('/report-business/{id}', 'Business\BusinessController@reportBusiness')->name('business.report');
    Route::get('/create-package/{id}', 'Business\BusinessController@createPackage')->name('business.createPackage');
    Route::get('/edit-package/{id}', 'Business\BusinessController@editPackage')->name('business.editPackage');
    Route::post('/store-package', 'Business\BusinessController@storePackage')->name('business.storePackage');
    Route::post('/edit-package', 'Business\BusinessController@updatePackage')->name('business.updatePackage');
    Route::post('/edit-notification', 'Business\BusinessController@updateNotification')->name('business.updateNotification');

    // Route::get('/track', 'Admin\MusisiPlatformController@track')->name('musisi-platform.track');
    // Route::get('/trackMusician', 'Admin\MusisiPlatformController@trackMusician')->name('musisi-platform.trackMusician');
    // Route::get('/band', 'Admin\MusisiPlatformController@band')->name('musisi-platform.band');
    // Route::get('/data', 'Admin\MusisiPlatformController@data')->name('musisi-platform.data');
    // Route::get('/dataBand', 'Admin\MusisiPlatformController@dataBand')->name('musisi-platform.dataBand');
    // Route::get('/dataTrack', 'Admin\MusisiPlatformController@dataTrack')->name('musisi-platform.dataTrack');
    // Route::get('/dataTrackMusician', 'Admin\MusisiPlatformController@dataTrackMusician')->name('musisi-platform.dataTrackMusician');
    // Route::get('musisi-platform/sync', 'Admin\MusisiPlatformController@sync')->name('musisi-platform.sync');
    // Route::get('musisi-platform/syncTrack', 'Admin\MusisiPlatformController@syncTrack')->name('musisi-platform.syncTrack');
    // Route::get('musisi-platform/syncTrackMusician', 'Admin\MusisiPlatformController@syncTrackMusician')->name('musisi-platform.syncTrackMusician');
    // Route::get('musisi-platform/syncBand', 'Admin\MusisiPlatformController@syncBand')->name('musisi-platform.syncBand');
});

Route::prefix('musisi-platform')->group(static function () {
    Route::get('/', 'Admin\MusisiPlatformController@index')->name('musisi-platform');
    Route::get('/track', 'Admin\MusisiPlatformController@track')->name('musisi-platform.track');
    Route::get('/trackMusician', 'Admin\MusisiPlatformController@trackMusician')->name('musisi-platform.trackMusician');
    Route::get('/band', 'Admin\MusisiPlatformController@band')->name('musisi-platform.band');
    Route::get('/data', 'Admin\MusisiPlatformController@data')->name('musisi-platform.data');
    Route::get('/dataBand', 'Admin\MusisiPlatformController@dataBand')->name('musisi-platform.dataBand');
    Route::get('/dataTrack', 'Admin\MusisiPlatformController@dataTrack')->name('musisi-platform.dataTrack');
    Route::get('/dataTrackMusician', 'Admin\MusisiPlatformController@dataTrackMusician')->name('musisi-platform.dataTrackMusician');
    Route::get('musisi-platform/sync', 'Admin\MusisiPlatformController@sync')->name('musisi-platform.sync');
    Route::get('musisi-platform/syncTrack', 'Admin\MusisiPlatformController@syncTrack')->name('musisi-platform.syncTrack');
    Route::get('musisi-platform/syncTrackMusician', 'Admin\MusisiPlatformController@syncTrackMusician')->name('musisi-platform.syncTrackMusician');
    Route::get('musisi-platform/syncBand', 'Admin\MusisiPlatformController@syncBand')->name('musisi-platform.syncBand');

    // Route::get('/data', 'Admin\BannerController@data')->name('banner.data');
    // Route::get('/create', 'Admin\BannerController@create')->name('banner.create');
    // Route::post('/store', 'Admin\BannerController@store')->name('banner.store');
    // Route::get('/edit', 'Admin\BannerController@edit')->name('banner.edit');
    // Route::post('/update', 'Admin\BannerController@update')->name('banner.update');
    // Route::get('/delete', 'Admin\BannerController@delete')->name('banner.delete');
    // Route::post('/destroy', 'Admin\BannerController@destroy')->name('banner.destroy');
    // Route::get('/show', 'Admin\BannerController@show')->name('banner.show');
});

Route::get('/home', 'HomeController@index')->name('home');

//Banner
Route::prefix('banner')->group(static function () {
    Route::get('/', 'Admin\BannerController@index')->name('banner');
    Route::get('/data', 'Admin\BannerController@data')->name('banner.data');
    Route::get('/create', 'Admin\BannerController@create')->name('banner.create');
    Route::post('/store', 'Admin\BannerController@store')->name('banner.store');
    Route::get('/edit', 'Admin\BannerController@edit')->name('banner.edit');
    Route::post('/update', 'Admin\BannerController@update')->name('banner.update');
    Route::get('/delete', 'Admin\BannerController@delete')->name('banner.delete');
    Route::post('/destroy', 'Admin\BannerController@destroy')->name('banner.destroy');
    Route::get('/show', 'Admin\BannerController@show')->name('banner.show');
});

//genre
Route::prefix('genre')->group(static function () {
    Route::get('/', 'Admin\GenreController@index')->name('genre');
    Route::get('/data', 'Admin\GenreController@data')->name('genre.data');
    Route::get('/create', 'Admin\GenreController@create')->name('genre.create');
    Route::post('/store', 'Admin\GenreController@store')->name('genre.store');
    Route::get('/edit', 'Admin\GenreController@edit')->name('genre.edit');
    Route::post('/update', 'Admin\GenreController@update')->name('genre.update');

app/NewsCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewsCategory extends Model
{
    //
    protected $table = 'news_category';
    protected $fillable = ['name','slug','enabled'];
}

app/Http/Controllers/Admin/NewsCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\NewsCategory;
use App\Services\Slug;
class NewsCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $NewsCategories = NewsCategory::orderBy('id','asc')->paginate(5);
  
        return view('admin.news-categories.index',compact('NewsCategories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.news-categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //        
        $data = $request->all();
        $request->validate([
            'name' => 'required',          
        ]);
        $slug = new Slug();
        $data['slug'] = $slug->createSlug($request->name);
        $data['enabled'] = true;
        

        NewsCategory::create($data);
   
        return redirect()->route('news-categories.index')
                        ->with('success','category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(NewsCategory $newsCategory)
    {
        //
        return view('admin.news-categories.show',compact('newsCategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(NewsCategory $newsCategory)
    {
        //        
        return view('admin.news-categories.edit',compact('newsCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, NewsCategory $newsCategory)
    {
        //
         //
         $data = $request->all();
         $request->validate([
            'name' => 'required',           
        ]);
        $slug = new Slug();
        $data['slug'] = $slug->createSlug($request->name);
        $data['enabled'] = true;
        

        $newsCategory->update($data);
   
  
        return redirect()->route('news-categories.index')
                        ->with('success','category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(NewsCategory $newsCategory)
    {
        //
        $newsCategory->delete();
  
        return redirect()->route('news-categories.index')
                        ->with('success','category deleted successfully');
    }
}

resources/views/admin/news-categories/create.blade.php
@extends('layouts.admin')
  
@section('content')

<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-8  offset-md-2">
                <div class="card no-b  no-r">

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('news-categories.store') }}" method="POST">
    @csrf
    <div class="card no-b  no-r">
    <div class="card-body">
        <h5 class="card-title">Create Category</h5>
        <hr>
        <div class="form-row">
            <div class="col-md-8">
                <div class="form-group m-0">
                    <label for="name" class="col-form-label s-12">CATEGORY NAME</label>
                    <input name="name" id="name" placeholder="Enter Category Name" class="form-control r-0 light s-12 " type="text">
                </div>
            </div>
        </div>
    </div>
    
    <hr>
    <div class="card-body">
        <button type="submit" class="btn btn-primary btn-sm"><i class="icon-save mr-2"></i>Save Data</button>
    </div>
</div>
</form>      
</div>
</div>
</div>
</div>
@endsection

resources/views/admin/news-categories/edit.blade.php
@extends('layouts.admin')
  
@section('content')

<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-7  offset-md-2">
                <div class="card no-b  no-r">

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('news-categories.update',$newsCategory->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="card no-b  no-r">
    <div class="card-body">
        <h5 class="card-title">Edit Category</h5>
        <hr>
        <div class="form-row">
            <div class="col-md-8">
                <div class="form-group m-0">
                    <label for="name" class="col-form-label s-12">CATEGORY NAME</label>
                    <input name="name" id="name" value="{{ $newsCategory->name }}" placeholder="Enter Category Name" class="form-control r-0 light s-12 " type="text">
                </div>
            </div>
        </div>
    </div>
    
    <hr>
    <div class="card-body">
        <button type="submit" class="btn btn-primary btn-sm"><i class="icon-save mr-2"></i>Save Data</button>
    </div>
</div>
</form>      
</div>
</div>
</div>
</div>
@endsection

resources/views/admin/news-categories/index.blade.php
@extends('layouts/admin')

@section('content')

<div class="container-fluid my-2">
<div class="row">
            <div class="col-md-12">
          

                            @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
                 
                            <table class="table table-bordered" style="background:white;">
                                <tr>
                                    <td colspan="3">
                                       <h4> News Category </h4>
                                    </td>
                                    <td>
                                    <a class="btn btn-success pull-right" href="{{ route('news-categories.create') }}"> Create New Category</a>
                                    </td>
                                </tr>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th width="280px">Action</th>
                                </tr>
                                @foreach ($NewsCategories as $type)
                                <tr>
                                    <td>{{ $type->id }}</td>
                                    <td>{{ $type->name }}</td>
                                    <td>{{ $type->slug }}</td>
                                    <td>
                                        <form action="{{ route('news-categories.destroy',$type->id) }}" method="POST">

                                            <a class="btn btn-info" href="{{ route('news-categories.show',$type->id) }}">Show</a>

                                            <a class="btn btn-primary" href="{{ route('news-categories.edit',$type->id) }}">Edit</a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                                <tr>
                                     <td colspan="4" align="center">
                                    {!! $NewsCategories->links() !!}
                                    </td>
                                </tr>
                            </table>
             
        </div>
    </div>

</div>


@endsection

resources/views/admin/news-categories/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container-fluid animatedParent animateOnce">
        <div class="animated fadeInUpShort">
            <div class="row my-3">
                <div class="col-md-7  offset-md-2">
                <div class="card no-b  no-r">

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h5> View detail</h5>
            </div>
            <hr>
            
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $newsCategory->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Slug:</strong>
                {{ $newsCategory->slug }}
            </div>
        </div>
    </div>
    </div>
    <hr>
    <div class="pull-right">
                <a class="btn btn-primary btn-sm" href="{{ route('news-categories.index') }}"> Back</a>
            </div>
</div>
</div>
</div>    
</div>    
@endsection